import React, { Profiler, useState } from "react";
import { useRef } from "react";
import { Alert, Modal, StyleSheet, TextInput, Pressable, View, Platform, StatusBar, SafeAreaView, Image, Text, Button, } from "react-native";


export default class GlobalData{
 rideList = [
    {
        id: '1',
        title: 'First Ride',
        location: 'UGH HIGH SCHOOL, GOSANI, Gosani, Odisha, India',
        destination: 'Hyderabad International Airport (HYD), Shamshabad, Hyderabad, Telangana, India',
        date: 'Sat , Feb 06',
        time: '12:05 PM',
        amount: 245.12,
        carType: 'Sedan',
    },
    {
        id: '2',
        title: 'Second Ride',
        location: 'Hyderabad International Airport (HYD), Shamshabad, Hyderabad, Telangana, India',
        destination: 'Delhi Airport, New Delhi, Delhi, India',
        date: 'Mon , Aug 06',
        time: '9:25 AM',
        amount: 501.00,
        carType: 'SUV',
    },
    {
        id: '3',
        title: 'Third Ride',
        location: 'US Consulate General, Chiran Fort Club Lane, Patigadda, Begumpet, Secunderabad, Telangana, India',
        destination: 'UGH HIGH SCHOOL, GOSANI, Gosani, Odisha, India',
        date: 'Sun , Mar 16',
        time: '1:45 PM',
        amount: 129.25,
        carType: 'Sedan',
    },
    {
        id: '4',
        title: 'Fourth Ride',
        location: 'Delhi Airport, New Delhi, Delhi, India',
        destination: 'US Consulate General, Chiran Fort Club Lane, Patigadda, Begumpet, Secunderabad, Telangana, India',
        date: 'Sat , Aug 12',
        time: '9:25 PM',
        amount: 199.00,
        carType: 'Prime SUV',
    },
    {
        id: '5',
        title: 'Fifth Ride',
        location: 'Hyderabad International Airport (HYD), Shamshabad, Hyderabad, Telangana, India',
        destination: 'Delhi Airport, New Delhi, Delhi, India',
        date: 'Sat , Feb 06',
        time: '06:25 AM',
        amount: 267.16,
        carType: 'Prime Sedan',
    },
    {
        id: '6',
        title: 'Sixth Ride',
        location: 'US Consulate General, Chiran Fort Club Lane, Patigadda, Begumpet, Secunderabad, Telangana, India',
        destination: 'Hyderabad International Airport (HYD), Shamshabad, Hyderabad, Telangana, India',
        date: 'Sat , Feb 06',
        time: '09:29 PM',
        amount: 309.24,
        carType: 'SUV',
    },
    {
        id: '7',
        title: 'Seventh Ride',
        location: 'Delhi Airport, New Delhi, Delhi, India',
        destination: 'UGH HIGH SCHOOL, GOSANI, Gosani, Odisha, India',
        date: 'Sat , Feb 06',
        time: '07:55 PM',
        amount: 150.75,
        carType: 'Sedan',
    },
    {
        id: '8',
        title: 'Eighth Ride',
        location: 'US Consulate General, Chiran Fort Club Lane, Patigadda, Begumpet, Secunderabad, Telangana, India',
        destination: 'UGH HIGH SCHOOL, GOSANI, Gosani, Odisha, India',
        date: 'Sat , Feb 06',
        time: '09:25 PM',
        amount: 230.40,
        carType: 'Sedan',
    },
    {
        id: '9',
        title: 'Nine Ride',
        location: 'hyderabad',
        destination: 'nizamabad',
        date: 'Sat , Feb 06',
        time: '4:35 PM',
        amount: 195.23,
        carType: 'Sedan',
    },
]
}